micronaut:
  application:
    name: demo
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: UPDATE
    dialect: ${JDBC_DIALECT:MYSQL}
    url: jdbc:mysql://localhost:3306/toDo_kotlin?createDatabaseIfNotExist=true
    username: user
    password: password
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        hbm2ddl:
          auto: update
        show_sql: true
